channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex
  - asttokens=2.0.5
  - backcall=0.2.0
  - blas=1.0
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2023.08.22
  - certifi=2023.7.22
  - cffi=1.15.1
  - comm=0.1.2
  - cryptography=41.0.3
  - cudatoolkit
  - debugpy=1.6.7
  - decorator=5.1.1
  - exceptiongroup=1.0.4
  - executing=0.8.3
  - ffmpeg=4.3
  - freetype=2.10.4
  - gmp=6.2.1
  - gnutls=3.6.13
  - idna=3.4
  - importlib-metadata=6.0.0
  - importlib_metadata=6.0.0
  - intel-openmp=2021.4.0
  - ipykernel=6.25.0
  - ipython=8.15.0
  - jbig=2.1
  - jedi=0.18.1
  - jpeg=9e
  - jupyter_client=8.1.0
  - jupyter_core=5.3.0
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=2.2.1
  - libdeflate=1.7
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgomp=11.2.0
  - libiconv=1.17
  - libpng=1.6.37
  - libsodium=1.0.18
  - libstdcxx-ng=11.2.0
  - libtiff=4.3.0
  - libuv=1.43.0
  - libwebp-base=1.2.2
  - lz4-c=1.9.3
  - matplotlib-inline=0.1.6
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - ncurses=6.4
  - nest-asyncio=1.5.6
  - nettle=3.6
  - numpy=1.24.3
  - numpy-base=1.24.3
  - olefile=0.46
  - openh264=2.1.1
  - openjpeg=2.4.0
  - openssl=3.0.11
  - parso=0.8.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=8.3.2
  - pip=23.2.1
  - platformdirs=3.10.0
  - pooch=1.7.0
  - prompt-toolkit=3.0.36
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.15.1
  - pyopenssl=23.2.0
  - pysocks=1.7.1
  - python=3.9.18
  - python-dateutil=2.8.2
  - python_abi=3.9
  - pytorch-mutex=1.0
  - pyzmq=25.1.0
  - readline=8.2
  - requests=2.31.0
  - scipy=1.10.1
  - setuptools=68.0.0
  - six=1.16.0
  - sqlite=3.41.2
  - stack_data=0.2.0
  - tk=8.6.12
  - torchaudio=0.10.1
  - torchvision=0.11.2
  - tornado=6.3.3
  - traitlets=5.7.1
  - typing_extensions=4.8.0
  - wcwidth=0.2.5
  - wheel=0.41.2
  - xz=5.4.2
  - zeromq=4.3.4
  - zipp=3.11.0
  - zlib=1.2.13
  - zstd=1.5.0
  - pip:
      - accelerate==0.24.1
      - aiohttp==3.8.5
      - aiosignal==1.3.1
      - appdirs==1.4.4
      - async-timeout==4.0.3
      - attrs==23.1.0
      - chardet==5.2.0
      - charset-normalizer==3.3.0
      - click==8.1.7
      - colorama==0.4.6
      - contourpy==1.2.0
      - cycler==0.12.1
      - datasets==2.16.1
      - dill==0.3.6
      - docker-pycreds==0.4.0
      - einops==0.7.0
      - evaluate==0.4.1
      - filelock==3.12.4
      - flash-attn==2.3.6
      - fonttools==4.45.1
      - frozenlist==1.4.0
      - fsspec==2023.9.2
      - gitdb==4.0.10
      - gitpython==3.1.37
      - huggingface-hub==0.20.2
      - importlib-resources==6.1.1
      - jinja2==3.1.2
      - kiwisolver==1.4.5
      - lxml==5.1.0
      - markupsafe==2.1.3
      - matplotlib==3.8.2
      - mpmath==1.3.0
      - multidict==6.0.4
      - multiprocess==0.70.14
      - networkx==3.2.1
      - ninja==1.11.1.1
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.18.1
      - nvidia-nvjitlink-cu12==12.3.101
      - nvidia-nvtx-cu12==12.1.105
      - packaging==23.2
      - pandas==2.1.1
      - pathtools==0.1.2
      - peft==0.6.2
      - plotly==5.18.0
      - portalocker==2.8.2
      - protobuf==4.24.4
      - psutil==5.9.5
      - pyarrow==13.0.0
      - pyarrow-hotfix==0.6
      - pyparsing==3.1.1
      - pytz==2023.3.post1
      - pyyaml==6.0.1
      - regex==2023.10.3
      - responses==0.18.0
      - sacrebleu==2.4.0
      - safetensors==0.4.0
      - sentencepiece==0.1.99
      - sentry-sdk==1.31.0
      - setproctitle==1.3.3
      - smmap==5.0.1
      - sympy==1.12
      - tabulate==0.9.0
      - tenacity==8.2.3
      - tokenizers==0.13.3
      - torch==2.1.1
      - tqdm==4.66.1
      - transformers==4.28.0
      - triton==2.1.0
      - tzdata==2023.3
      - urllib3==2.0.6
      - wandb==0.15.12
      - xxhash==3.4.1
      - yarl==1.9.2
